baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft Starter'
primary: true
siteGroup: 199da6d9-e106-47e8-ba2d-b57e54288649 # Craft Starter
sortOrder: 1
