currLabel: Assets
customIcon: null
enabled: true
handle: assets
icon: assets
layout: 44a3b77d-ef90-4a52-ad2c-d50bc9c6a273 # Default
newWindow: false
order: 1
prevLabel: Assets
prevUrl: assets
type: ''
url: assets
