currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: settings
layout: 44a3b77d-ef90-4a52-ad2c-d50bc9c6a273 # Default
newWindow: false
order: 5
prevLabel: Settings
prevUrl: settings
type: ''
url: settings
