currLabel: Utilities
customIcon: null
enabled: true
handle: utilities
icon: tool
layout: 44a3b77d-ef90-4a52-ad2c-d50bc9c6a273 # Default
newWindow: false
order: 4
prevLabel: Utilities
prevUrl: utilities
type: ''
url: utilities
